### ISSUE TITLE
Accounts

### ISSUE THREAD

**Issue by sirspock** [csrg-utfsm/csrg#15]
Create accounts for all users of Valparaíso. Please, follow the standard of Santiago: the home has to be in: /users/cnunez (example: /users/cnunez)

You can see users running:

```
ldapsearch -x uid=* | grep uid:
```

**Comment by cjauregu** [comment]
- User accounts have been created or modified according to the case.
- For old users, the path of the home folder has been configured.
- For new users, a new LDAP registry has been created and they have a secure temporary password.

<table dir="ltr" border="1" cellspacing="0" cellpadding="0"><colgroup><col width="100" /><col width="100" /><col width="100" /><col width="216" /><col width="100" /></colgroup>
<tbody>
<tr>
<td data-sheets-value="{&quot;1&quot;:2,&quot;2&quot;:&quot;Valparaiso&quot;}">Valparaiso</td>
<td>&nbsp;</td>
<td>&nbsp;</td>
<td>&nbsp;</td>
<td>&nbsp;</td>
</tr>
<tr>
<td data-sheets-value="{&quot;1&quot;:2,&quot;2&quot;:&quot;Name&quot;}">Name</td>
<td data-sheets-value="{&quot;1&quot;:2,&quot;2&quot;:&quot;Full Name&quot;}">Full Name</td>
<td data-sheets-value="{&quot;1&quot;:2,&quot;2&quot;:&quot;UID&quot;}">UID</td>
<td data-sheets-value="{&quot;1&quot;:2,&quot;2&quot;:&quot;Home directory&quot;}">Home directory</td>
<td>&nbsp;</td>
</tr>
<tr>
<td data-sheets-value="{&quot;1&quot;:2,&quot;2&quot;:&quot;mosorio&quot;}">mosorio</td>
<td data-sheets-value="{&quot;1&quot;:2,&quot;2&quot;:&quot;Maximiliano&quot;}">Maximiliano</td>
<td data-sheets-value="{&quot;1&quot;:3,&quot;3&quot;:1009}">1009</td>
<td data-sheets-value="{&quot;1&quot;:2,&quot;2&quot;:&quot;/users/mosorio&quot;}">/users/mosorio</td>
<td>&nbsp;</td>
</tr>
<tr>
<td data-sheets-value="{&quot;1&quot;:2,&quot;2&quot;:&quot;racacere&quot;}">racacere</td>
<td data-sheets-value="{&quot;1&quot;:2,&quot;2&quot;:&quot;rodrigo&quot;}">rodrigo</td>
<td data-sheets-value="{&quot;1&quot;:3,&quot;3&quot;:1144}">1144</td>
<td data-sheets-value="{&quot;1&quot;:2,&quot;2&quot;:&quot;/users/racacere&quot;}">/users/racacere</td>
<td>&nbsp;</td>
</tr>
<tr>
<td data-sheets-value="{&quot;1&quot;:2,&quot;2&quot;:&quot;cponce&quot;}">cponce</td>
<td data-sheets-value="{&quot;1&quot;:2,&quot;2&quot;:&quot;carlos&quot;}">carlos</td>
<td data-sheets-value="{&quot;1&quot;:3,&quot;3&quot;:1141}">1141</td>
<td data-sheets-value="{&quot;1&quot;:2,&quot;2&quot;:&quot;/users/cponce&quot;}">/users/cponce</td>
<td>&nbsp;</td>
</tr>
<tr>
<td data-sheets-value="{&quot;1&quot;:2,&quot;2&quot;:&quot;cjauregui&quot;}">cjauregui</td>
<td data-sheets-value="{&quot;1&quot;:2,&quot;2&quot;:&quot;Carlos&quot;}">Carlos</td>
<td data-sheets-value="{&quot;1&quot;:3,&quot;3&quot;:1112}">1112</td>
<td data-sheets-value="{&quot;1&quot;:2,&quot;2&quot;:&quot;/users/cjauregui&quot;}">/users/cjauregui</td>
<td>&nbsp;</td>
</tr>
<tr>
<td data-sheets-value="{&quot;1&quot;:2,&quot;2&quot;:&quot;maray&quot;}">maray</td>
<td data-sheets-value="{&quot;1&quot;:2,&quot;2&quot;:&quot;Mauricio&quot;}">Mauricio</td>
<td data-sheets-value="{&quot;1&quot;:3,&quot;3&quot;:1106}">1106</td>
<td data-sheets-value="{&quot;1&quot;:2,&quot;2&quot;:&quot;/users/maray&quot;}">/users/maray</td>
<td>&nbsp;</td>
</tr>
<tr>
<td data-sheets-value="{&quot;1&quot;:2,&quot;2&quot;:&quot;legutier&quot;}">legutier</td>
<td data-sheets-value="{&quot;1&quot;:2,&quot;2&quot;:&quot;Lukas&quot;}">Lukas</td>
<td data-sheets-value="{&quot;1&quot;:3,&quot;3&quot;:1143}">1143</td>
<td data-sheets-value="{&quot;1&quot;:2,&quot;2&quot;:&quot;/users/legutier&quot;}">/users/legutier</td>
<td>&nbsp;</td>
</tr>
<tr>
<td data-sheets-value="{&quot;1&quot;:2,&quot;2&quot;:&quot;fcasas&quot;}">fcasas</td>
<td data-sheets-value="{&quot;1&quot;:2,&quot;2&quot;:&quot;Francisco&quot;}">Francisco</td>
<td data-sheets-value="{&quot;1&quot;:3,&quot;3&quot;:1004}">1004</td>
<td data-sheets-value="{&quot;1&quot;:2,&quot;2&quot;:&quot;/users/fcasas&quot;}">/users/fcasas</td>
<td data-sheets-value="{&quot;1&quot;:2,&quot;2&quot;:&quot;new user&quot;}">new user</td>
</tr>
<tr>
<td data-sheets-value="{&quot;1&quot;:2,&quot;2&quot;:&quot;pcampana&quot;}">pcampana</td>
<td data-sheets-value="{&quot;1&quot;:2,&quot;2&quot;:&quot;Patricio&quot;}">Patricio</td>
<td data-sheets-value="{&quot;1&quot;:3,&quot;3&quot;:1142}">1142</td>
<td data-sheets-value="{&quot;1&quot;:2,&quot;2&quot;:&quot;/users/pcampana&quot;}">/users/pcampana</td>
<td>&nbsp;</td>
</tr>
<tr>
<td data-sheets-value="{&quot;1&quot;:2,&quot;2&quot;:&quot;vlizana&quot;}">vlizana</td>
<td data-sheets-value="{&quot;1&quot;:2,&quot;2&quot;:&quot;Vicente&quot;}">Vicente</td>
<td data-sheets-value="{&quot;1&quot;:3,&quot;3&quot;:1005}">1005</td>
<td data-sheets-value="{&quot;1&quot;:2,&quot;2&quot;:&quot;/users/vlizana&quot;}">/users/vlizana</td>
<td data-sheets-value="{&quot;1&quot;:2,&quot;2&quot;:&quot;new user&quot;}">new user</td>
</tr>
<tr>
<td data-sheets-value="{&quot;1&quot;:2,&quot;2&quot;:&quot;arodrigu&quot;}">arodrigu</td>
<td data-sheets-value="{&quot;1&quot;:2,&quot;2&quot;:&quot;Andrea&quot;}">Andrea</td>
<td data-sheets-value="{&quot;1&quot;:3,&quot;3&quot;:1007}">1007</td>
<td data-sheets-value="{&quot;1&quot;:2,&quot;2&quot;:&quot;/users/arodrigu&quot;}">/users/arodrigu</td>
<td data-sheets-value="{&quot;1&quot;:2,&quot;2&quot;:&quot;new user&quot;}">new user</td>
</tr>
<tr>
<td data-sheets-value="{&quot;1&quot;:2,&quot;2&quot;:&quot;nmtapia&quot;}">nmtapia</td>
<td data-sheets-value="{&quot;1&quot;:2,&quot;2&quot;:&quot;Nicolas&quot;}">Nicolas</td>
<td data-sheets-value="{&quot;1&quot;:3,&quot;3&quot;:1010}">1010</td>
<td data-sheets-value="{&quot;1&quot;:2,&quot;2&quot;:&quot;/users/nmtapia&quot;}">/users/nmtapia</td>
<td data-sheets-value="{&quot;1&quot;:2,&quot;2&quot;:&quot;new user&quot;}">new user</td>
</tr>
<tr>
<td data-sheets-value="{&quot;1&quot;:2,&quot;2&quot;:&quot;fquiroz&quot;}">fquiroz</td>
<td data-sheets-value="{&quot;1&quot;:2,&quot;2&quot;:&quot;Frank&quot;}">Frank</td>
<td data-sheets-value="{&quot;1&quot;:3,&quot;3&quot;:1015}">1015</td>
<td data-sheets-value="{&quot;1&quot;:2,&quot;2&quot;:&quot;/users/fquiroz&quot;}">/users/fquiroz</td>
<td data-sheets-value="{&quot;1&quot;:2,&quot;2&quot;:&quot;new user&quot;}">new user</td>
</tr>
<tr>
<td data-sheets-value="{&quot;1&quot;:2,&quot;2&quot;:&quot;mavillan&quot;}">mavillan</td>
<td data-sheets-value="{&quot;1&quot;:2,&quot;2&quot;:&quot;Martin&quot;}">Martin</td>
<td data-sheets-value="{&quot;1&quot;:3,&quot;3&quot;:1107}">1107</td>
<td data-sheets-value="{&quot;1&quot;:2,&quot;2&quot;:&quot;/users/mavillan&quot;}">/users/mavillan</td>
<td>&nbsp;</td>
</tr>
<tr>
<td data-sheets-value="{&quot;1&quot;:2,&quot;2&quot;:&quot;cvalenzu&quot;}">cvalenzu</td>
<td data-sheets-value="{&quot;1&quot;:2,&quot;2&quot;:&quot;Camilo&quot;}">Camilo</td>
<td data-sheets-value="{&quot;1&quot;:3,&quot;3&quot;:1140}">1140</td>
<td data-sheets-value="{&quot;1&quot;:2,&quot;2&quot;:&quot;/users/cvalenzu&quot;}">/users/cvalenzu</td>
<td>&nbsp;</td>
</tr>
<tr>
<td data-sheets-value="{&quot;1&quot;:2,&quot;2&quot;:&quot;abayo&quot;}">abayo</td>
<td data-sheets-value="{&quot;1&quot;:2,&quot;2&quot;:&quot;amelia&quot;}">amelia</td>
<td data-sheets-value="{&quot;1&quot;:3,&quot;3&quot;:1111}">1111</td>
<td data-sheets-value="{&quot;1&quot;:2,&quot;2&quot;:&quot;/users/abayo&quot;}">/users/abayo</td>
<td>&nbsp;</td>
</tr>
</tbody>
</table>

**Comment by sirspock** [comment]
nice

**Comment by cjauregu** [comment]
mb

solved 🖒
