### ISSUE TITLE
Centos 7 - ovirt template

### ISSUE THREAD

**Issue by sirspock** [csrg-utfsm/csrg#18]
We need a template of Centos 7.5.

Requirements:
- Add ssh keys: @capgadsx @cjauregu @sirspock

Maybe, this is a good guide:
https://github.com/rharmonson/richtech/wiki/CentOS-7-1511-Minimal-oVirt-Template

**Comment by sirspock** [comment]
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCytYY04VicQYjofpEL1G3iWWD2yOoH5ubTqgT7kwDfbfR6xAFxlRZpEBut28KjrQ5zxnMy6cHO293/5ZRNxL4dzvhXye2LqxHLAMxWJmIUkKzUGnJKFFP+Dt+GVlyDQyycrmneASFU1KzpEmeH5vR6ItnrUkd5hvU3/tEyf27gVvKhmVIvwkxf4UsFX0L6kbop+rJwr3n4BhngVOjY3wPDN5OM1LvuqLll3ci/9T2WdOlEbxU8qJDbRLNIDx0I7x/uDCAHOPzZ1SSzIUaq+Qavi+myeeHxB5YR01f+UxbC4RvcFpQoyxf+KjACWheB18sXk5hJWMBYevyHP6JB3hg9mFeSv7AzU7/+tkXpF8cfVGJb1BKIIyAY7eRJHDu9REAZL0+75PYDbo/EBfIfB0asr8HpJ7C89gRnQdXlpa+IZwZsp2Ooki3smQO9FBcACefde6VNyCWx+cVXILNcWde8MP+gldmr8ueHmIDuRNESoe1n+KNqsf7LM2zTyRHvyZ5Zdfgyjx3SvxvWPDNDxUnSJ8W2i+QiVhRhUcYg4aK3BfueknvfYBHkZ+aHHGwEiXhcUotuiHCjIuvQd6oD9Y5+AhA2tqpvQgdGUny1LWK5NM0UIZA48elA6kVvl/kij26d0rB2A6bW6yu3aVxj3cAQvl77Lz2ojIMw2gkAVQ2Qzw== mosorio key labcomp

**Comment by cjauregu** [comment]
I could not get the CentOS 7.5 image, could someone get it? (halp: S)

A CentOS 7.4.1708 template has been created and tested, this is the first version that will be updated according to your comments.
_template name: CentOS_7.4_Server_Template_

A VM has been created using this template, if you want you can login via ssh and check the configuration. 
_VM name: test_template 10.6.91.221_

**Comment by LeoXDXp** [comment]
The template shows the disk as preallocated. This isn't the best policy.

**Comment by cjauregu** [comment]
the template has been updated according to your comments.
Please, create a new VMs using the template and check that everything is OK

**Comment by capgadsx** [comment]
I've checked @cjauregu changes in the template, and they looks good to me, firewalld is enabled, the disk is now sparse (thin provisioned) instead of preallocated, ssh keys of admins were added and the default root password has been set.

Waiting for @sirspock approval to close the issue.

**Comment by sirspock** [comment]
Looks good
