### ISSUE TITLE
paper overview

### ISSUE THREAD

**Issue by sirspock** [csrg-utfsm/csrg#2]
- Understand the pipeline
- cryptic results

**Comment by sirspock** [comment]
Please close issue

**Comment by Autopawn** [comment]
Full summary of the latest paper completed on [the wiki page](https://github.com/csrg-utfsm/csrg/wiki/Application-of-Deep-Learning-methods-to-analysis-of-Imaging-Atmospheric-Cherenkov-Telescopes-data).
