### ISSUE TITLE
Create vm for student

### ISSUE THREAD

**Issue by sirspock** [csrg-utfsm/csrg#20]
Hernán Herreros Niño <hernan.herreros.13@sansano.usm.cl> needs a virtual machine for his undergraduate, final project. 

Requerimients:
* Centos 7

**Comment by sirspock** [comment]
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQD4d3QapU1UqyZVWAPPIlnlwsoqFu8G2hSy66w9mDJ6atnbLeu1fn10V82GjKMfRiskPm1ItJN5d41OEIn/pBh8M0qStq6AJHEa/e/ar+5ObNFhoXD8vY7eqSXCoP816U2z92WGOqNkxNkdA3ln+XuTr0ufY9/lpChfKXrHquMTR0Tmq8AeebP8fZ7PdZUwbCzMvFJshyysNv5smNj5Q2HnNtRVcVYMiEVROnIoVeo9udWE7SBiG+hr2Zk3dDevguP4jY4iZ2YmEnBtf0esF7cClJ2lJOggj0i+MjAIuUJHbPDuLt8gc0s+vn8tZpo3o6228pEczDy2IBJ2NHWpk7aX+BoL9luO5oHxwCTwwzONm1lxF7u0aq/CoTJnKEuZCyyTScwUk0lXJ8RY+T3GmzOhMqI6BcaRPEAclIEy73+X1Lg6s4ISw31RFDObJCK/WX/6CA5+/dxWl+RMYXVX0FV+4EKdlqE1frAioGxI61mnTgL0Fr8D03yRj5f/rVZqYffy4lObqnCNCe1KT8G0PmHRFGjNOq4cIkTxH6CgPwGdrzwCNa4ezWOgdQhoHKpvitWCgamjkFk0xCRIpwTgMGj2Mng6EJ83kbpOqR56AJ/dcd6CO5PqbIOWR1oP8c4mMULfw/e4h8zB8t/tcEeSeMHRo5PZkcGQA9PQwDtDFbbHYw==hernan.herreros@gmail.com

**Comment by capgadsx** [comment]
Waiting until #18 is solved.
