### ISSUE TITLE
Course: Radio astronomy for engineers

### ISSUE THREAD

**Issue by sirspock** [csrg-utfsm/csrg#7]
A few slides to explain...

**Comment by sirspock** [comment]
https://science.nrao.edu/facilities/alma/naasc-workshops/nrao-cd-wm16/BasicsInterf_Madison.pdf

**Comment by sirspock** [comment]
Please share the presentation. https://github.com/csrg-utfsm/csrg/tree/master/presentations

**Comment by vlizanae** [comment]
done!
https://github.com/csrg-utfsm/csrg/blob/master/presentations/basic-interferometry/Presentation.ipynb
