### ISSUE TITLE
Ovirt

### ISSUE THREAD

**Issue by sirspock** [csrg-utfsm/csrg#9]
- [x] Integration with LDAP
- [ ] DNS Domain + Lets encrypt

**Comment by capgadsx** [comment]
Implemented the LDAP Integration

**Comment by capgadsx** [comment]
For documentation purposes, the LDAP implementation used in the `ovirt-engine-extension-aaa-ldap-setup` stage was **`OpenLDAP RFC-2307 Schema`**. The role added to users is `PowerUserRole` and for admins is the `SuperUser` role.

**Comment by capgadsx** [comment]
@racacere Me esta trolleando mucho, halp

**Comment by capgadsx** [comment]
Implemented SSL for `ovirt.chivo.cl` with Let's Encrypt.
SSL Certificate dates:
```
notBefore=Apr 12 22:30:39 2018 GMT
notAfter=Jul 11 22:30:39 2018 GMT
```
